---
inventory:

  plugin: SimpleInventory
  options:
   host_file: "hosts29oct2022.yml"
   group_file: "groups29oct2022.yml"
   defaults_file: "defaults29oct2022.yml"


runners:
  plugin: threaded
  options:
   num_workers: 100


...